// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSzzenzGCfLFWBQaDJHGrghQOOetX0gco',
    appId: '1:398588851602:web:7fa3e08c6b142446b83d4b',
    messagingSenderId: '398588851602',
    projectId: 'cricket-scorer-eb2d3',
    authDomain: 'cricket-scorer-eb2d3.firebaseapp.com',
    storageBucket: 'cricket-scorer-eb2d3.firebasestorage.app',
    measurementId: 'G-HCWTWSB5V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPdgMNlaxdMjlGO9yhRF4nI0MDk6dnPoM',
    appId: '1:398588851602:android:c4bdb604c12d698ab83d4b',
    messagingSenderId: '398588851602',
    projectId: 'cricket-scorer-eb2d3',
    storageBucket: 'cricket-scorer-eb2d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALSb0ta1HBLc3iLWveeSwXonreBXeLYwA',
    appId: '1:398588851602:ios:19ee81f136625b7cb83d4b',
    messagingSenderId: '398588851602',
    projectId: 'cricket-scorer-eb2d3',
    storageBucket: 'cricket-scorer-eb2d3.firebasestorage.app',
    iosBundleId: 'A.Ahad.cricketScorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALSb0ta1HBLc3iLWveeSwXonreBXeLYwA',
    appId: '1:398588851602:ios:19ee81f136625b7cb83d4b',
    messagingSenderId: '398588851602',
    projectId: 'cricket-scorer-eb2d3',
    storageBucket: 'cricket-scorer-eb2d3.firebasestorage.app',
    iosBundleId: 'A.Ahad.cricketScorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSzzenzGCfLFWBQaDJHGrghQOOetX0gco',
    appId: '1:398588851602:web:79090f607e9392b6b83d4b',
    messagingSenderId: '398588851602',
    projectId: 'cricket-scorer-eb2d3',
    authDomain: 'cricket-scorer-eb2d3.firebaseapp.com',
    storageBucket: 'cricket-scorer-eb2d3.firebasestorage.app',
    measurementId: 'G-ZHLLP944JE',
  );
}
